### PR TITLE
fix fprintf arguments

### PR DESCRIPTION
**Pull request by Karry**
arguments are not matching formating string, when ssl is enabled... 
```
../../perdition/options.c:1767:5: warning: format ‘%d’ expects argument of type ‘int’, but argument 34 has type ‘const char *’ [-Wformat=]
 1767 |     "perdition version %s Copyright Horms\n"
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../perdition/options.c:1924:20: note: format string is defined here
 1924 |     "    (default %d)\n"
      |                   ~^
      |                    |
      |                    int
      |                   %s
```
and perdition is crashing with `--help` argument...

### CODE REVIEW

**Review by horms — CHANGES_REQUESTED** [review]
I think the problem here is that there are two many arguments for the format string.
The proposed patch takes the approach of removing the extra argument.
But I think it would be better to add the missing portion of the format string
for the --ssl_dh_params_file option.

Also, please consider a more informative changelog entry.
The one's in the history may not be great, but going forward let's try to do better.

I'd also like to move towards using signed-off-by tags, as the Linux kernel and many other projects do (you should replace mine with yours).

Something like this:

Add help format string for --ssl_dh_params_file option

Add missing portion of format string for --help output for the --ssl_dh_params_file option.
The absence of this means that there currently are too many arguments for the format string.

$ make
...
../../perdition/options.c:1767:5: warning: format ‘%d’ expects argument of type ‘int’, but argument 34 has type ‘const char *’ [-Wformat=]
 1767 |     "perdition version %s Copyright Horms\n"
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../perdition/options.c:1924:20: note: format string is defined here
 1924 |     "    (default %d)\n"
 
 Signed-off-by: Simon Horman <horms@verge.net.au>

**Comment by Karry** [comment]
Ou, sorry. I did not notice that there actually is --ssl_dh_params_file option. Here is updated fix.

**Comment by horms** [comment]
Thanks, applied: https://github.com/horms/perdition/commit/9215767c93bbc90797e3555f336e54b808fa6e79

**Comment by Karry** [comment]
It was pleasure. Thank you for taking care of this project.

**Pull request closed without merging**
